version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-smhd-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ny8y25mlfel9"
s3_prefix = "sam-smhd-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
